/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:ad7e0c69-b8ca-4afc-84e1-c29da300eb09",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_N57mLSVnN",
    "aws_user_pools_web_client_id": "5qsh34h3rv5ibu7o2vcv7dmn9u",
    "oauth": {}
};


export default awsmobile;
